CREATE TYPE "estado_empresa" AS ENUM (
  'activa',
  'inactiva'
);

CREATE TYPE "rol_usuario" AS ENUM (
  'admin_sistema',
  'cliente_empresa',
  'supervisor',
  'conductor'
);

CREATE TYPE "estado_conductor" AS ENUM (
  'disponible',
  'en_ruta',
  'no_disponible'
);

CREATE TYPE "modalidad_servicio" AS ENUM (
  'suscripcion',
  'pago_por_uso'
);

CREATE TYPE "estado_suscripcion" AS ENUM (
  'activa',
  'inactiva',
  'vencida'
);

CREATE TYPE "ciclo_facturacion" AS ENUM (
  'mensual',
  'anual'
);

CREATE TYPE "tipo_movimiento_credito" AS ENUM (
  'renovacion',
  'consumo',
  'compra'
);

CREATE TYPE "tipo_orden" AS ENUM (
  'entrega',
  'recogida'
);

CREATE TYPE "canal_orden" AS ENUM (
  'whatsapp',
  'llamada',
  'presencial'
);

CREATE TYPE "estado_orden" AS ENUM (
  'pendiente',
  'asignada',
  'completada',
  'cancelada'
);

CREATE TYPE "prioridad_orden" AS ENUM (
  'normal',
  'urgente'
);

CREATE TYPE "estado_ruta" AS ENUM (
  'registrada',
  'optimizada',
  'en_curso',
  'completada',
  'cancelada'
);

CREATE TYPE "estado_parada" AS ENUM (
  'pendiente',
  'llegada',
  'completada'
);

CREATE TYPE "clase_incidencia" AS ENUM (
  'incidencia',
  'duda'
);

CREATE TYPE "estado_incidencia" AS ENUM (
  'abierta',
  'en_proceso',
  'resuelta'
);

CREATE TYPE "estado_soporte" AS ENUM (
  'abierta',
  'respondida',
  'cerrada'
);

CREATE TYPE "severidad_alerta" AS ENUM (
  'informativa',
  'advertencia',
  'critica'
);

CREATE TYPE "concepto_pago" AS ENUM (
  'suscripcion',
  'paquete_creditos',
  'modulo',
  'consumo'
);

CREATE TYPE "estado_cobro_consumo" AS ENUM (
  'en_curso',
  'cobrado',
  'rechazado'
);

CREATE TYPE "estado_pago" AS ENUM (
  'pendiente',
  'aprobado',
  'rechazado'
);

CREATE TABLE "empresas" (
  "id" uuid PRIMARY KEY,
  "razon_social" varchar(200) NOT NULL,
  "nit" varchar(20) UNIQUE NOT NULL,
  "correo" varchar(150) NOT NULL,
  "telefono" varchar(30),
  "direccion" varchar(255),
  "estado" estado_empresa NOT NULL DEFAULT 'activa',
  "tiene_flota_propia" boolean NOT NULL,
  "configuracion" jsonb,
  "referencia_tarjeta" varchar(100),
  "tope_gasto_mensual" decimal(12,2),
  "fecha_registro" date NOT NULL DEFAULT (current_date)
);

CREATE TABLE "sedes" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "direccion" varchar(255)
);

CREATE TABLE "usuarios" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid,
  "rol" rol_usuario NOT NULL,
  "nombre_completo" varchar(150) NOT NULL,
  "correo" varchar(150) UNIQUE NOT NULL,
  "contrasena_hash" varchar(255) NOT NULL,
  "telefono" varchar(30),
  "activo" boolean NOT NULL DEFAULT true,
  "fecha_registro" date NOT NULL DEFAULT (current_date)
);

CREATE TABLE "conductores" (
  "usuario_id" uuid PRIMARY KEY,
  "estado" estado_conductor NOT NULL DEFAULT 'no_disponible'
);

CREATE TABLE "planes" (
  "id" uuid PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "modalidad" modalidad_servicio NOT NULL DEFAULT 'suscripcion',
  "max_conductores" int,
  "max_sedes" int,
  "tipo_soporte" varchar(50),
  "dias_prueba" int,
  "creditos_mensuales" int,
  "precio_mensual" decimal(12,2),
  "precio_anual" decimal(12,2),
  "conductores_incluidos" int,
  "precio_optimizacion" decimal(12,2),
  "precio_conductor_adicional" decimal(12,2),
  "monto_cobro_anticipado" decimal(12,2),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "suscripciones" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "plan_id" uuid NOT NULL,
  "estado" estado_suscripcion NOT NULL DEFAULT 'activa',
  "ciclo_facturacion" ciclo_facturacion,
  "pago_id" uuid,
  "fecha_inicio" date NOT NULL,
  "fecha_renovacion" date,
  "fecha_fin" date
);

CREATE TABLE "modulos" (
  "id" uuid PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "precio" decimal(12,2),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "planes_modulos" (
  "plan_id" uuid,
  "modulo_id" uuid,
  PRIMARY KEY ("plan_id", "modulo_id")
);

CREATE TABLE "empresas_modulos" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "modulo_id" uuid NOT NULL,
  "pago_id" uuid NOT NULL,
  "precio" decimal(12,2),
  "fecha_inicio" date NOT NULL DEFAULT (current_date),
  "fecha_fin" date
);

CREATE TABLE "saldos_creditos" (
  "empresa_id" uuid PRIMARY KEY,
  "creditos_plan" int NOT NULL DEFAULT 0,
  "creditos_extra" int NOT NULL DEFAULT 0
);

CREATE TABLE "paquetes_creditos" (
  "id" uuid PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "creditos" int NOT NULL,
  "precio" decimal(12,2) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "compras_creditos" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "paquete_id" uuid NOT NULL,
  "pago_id" uuid NOT NULL,
  "creditos" int NOT NULL,
  "precio" decimal(12,2) NOT NULL,
  "fecha_compra" date NOT NULL DEFAULT (current_date)
);

CREATE TABLE "movimientos_creditos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "tipo" tipo_movimiento_credito NOT NULL,
  "cantidad" int NOT NULL,
  "saldo_resultante" int NOT NULL,
  "compra_id" uuid,
  "optimizacion_id" uuid,
  "fecha" date NOT NULL DEFAULT (current_date)
);

CREATE TABLE "ordenes" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "sede_id" uuid,
  "tipo" tipo_orden NOT NULL,
  "direccion" varchar(255) NOT NULL,
  "latitud" decimal(9,6),
  "longitud" decimal(9,6),
  "prioridad" prioridad_orden NOT NULL DEFAULT 'normal',
  "nombre_cliente" varchar(150),
  "telefono_cliente" varchar(30),
  "descripcion" text,
  "canal" canal_orden,
  "estado" estado_orden NOT NULL DEFAULT 'pendiente',
  "fecha_registro" date NOT NULL DEFAULT (current_date)
);

CREATE TABLE "rutas" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "conductor_id" uuid,
  "fecha_ruta" date NOT NULL,
  "estado" estado_ruta NOT NULL DEFAULT 'registrada',
  "latitud_inicio" decimal(9,6),
  "longitud_inicio" decimal(9,6),
  "fecha_inicio" timestamp,
  "fecha_fin" timestamp
);

CREATE TABLE "paradas_ruta" (
  "id" uuid PRIMARY KEY,
  "ruta_id" uuid NOT NULL,
  "orden_id" uuid,
  "estudiante_id" uuid,
  "secuencia" int NOT NULL,
  "estado" estado_parada NOT NULL DEFAULT 'pendiente',
  "fecha_llegada" timestamp,
  "verificada_geocerca" boolean NOT NULL DEFAULT false,
  "fecha_confirmacion" timestamp,
  "fecha_sincronizacion" timestamp,
  "observaciones" text,
  "nombre_receptor" varchar(150)
);

CREATE TABLE "optimizaciones_ruta" (
  "id" uuid PRIMARY KEY,
  "ruta_id" uuid NOT NULL,
  "distancia_total_m" int,
  "duracion_estimada_s" int,
  "tiempo_procesamiento_ms" int,
  "exitosa" boolean NOT NULL,
  "cobro_consumo_id" uuid,
  "fecha" date NOT NULL DEFAULT (current_date)
);

CREATE TABLE "ubicaciones_ruta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruta_id" uuid NOT NULL,
  "latitud" decimal(9,6) NOT NULL,
  "longitud" decimal(9,6) NOT NULL,
  "fecha_captura" timestamp NOT NULL,
  "fecha_sincronizacion" timestamp NOT NULL DEFAULT (now()),
  "sin_conexion" boolean NOT NULL DEFAULT false
);

CREATE TABLE "fotos_entrega" (
  "id" uuid PRIMARY KEY,
  "parada_id" uuid NOT NULL,
  "url_foto" varchar(500) NOT NULL,
  "fecha_captura" timestamp
);

CREATE TABLE "incidencias" (
  "id" uuid PRIMARY KEY,
  "ruta_id" uuid NOT NULL,
  "parada_id" uuid,
  "clase" clase_incidencia NOT NULL,
  "descripcion" text NOT NULL,
  "estado" estado_incidencia NOT NULL DEFAULT 'abierta',
  "notas_resolucion" text,
  "fecha_reporte" timestamp NOT NULL DEFAULT (now()),
  "fecha_resolucion" timestamp
);

CREATE TABLE "mensajes_incidencia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "incidencia_id" uuid NOT NULL,
  "remitente_id" uuid NOT NULL,
  "mensaje" text NOT NULL,
  "fecha_envio" timestamp NOT NULL DEFAULT (now()),
  "fecha_lectura" timestamp
);

CREATE TABLE "solicitudes_soporte" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "asunto" varchar(200) NOT NULL,
  "descripcion" text NOT NULL,
  "estado" estado_soporte NOT NULL DEFAULT 'abierta',
  "respuesta" text,
  "fecha_envio" date NOT NULL DEFAULT (current_date),
  "fecha_respuesta" date
);

CREATE TABLE "alertas_sistema" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" uuid,
  "severidad" severidad_alerta NOT NULL,
  "origen" varchar(100),
  "mensaje" text NOT NULL,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "fecha_resolucion" timestamp
);

CREATE TABLE "configuracion_sistema" (
  "clave" varchar(100) PRIMARY KEY,
  "valor" jsonb NOT NULL,
  "fecha_actualizacion" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "notificaciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" uuid NOT NULL,
  "tipo" varchar(50) NOT NULL,
  "mensaje" text NOT NULL,
  "leida" boolean NOT NULL DEFAULT false,
  "fecha_registro" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "estudiantes" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "nombre_completo" varchar(150) NOT NULL,
  "direccion_recogida" varchar(255) NOT NULL,
  "latitud" decimal(9,6),
  "longitud" decimal(9,6),
  "activo" boolean NOT NULL DEFAULT true,
  "fecha_registro" date NOT NULL DEFAULT (current_date)
);

CREATE TABLE "pagos" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "concepto" concepto_pago NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "medio_pago" varchar(30),
  "estado" estado_pago NOT NULL DEFAULT 'pendiente',
  "referencia_pasarela" varchar(100) UNIQUE,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "fecha_aprobacion" timestamp
);

CREATE TABLE "cobros_consumo" (
  "id" uuid PRIMARY KEY,
  "empresa_id" uuid NOT NULL,
  "fecha_inicio_periodo" date NOT NULL,
  "fecha_fin_periodo" date,
  "cantidad_optimizaciones" int NOT NULL DEFAULT 0,
  "conductores_adicionales" int NOT NULL DEFAULT 0,
  "monto" decimal(12,2) NOT NULL DEFAULT 0,
  "estado" estado_cobro_consumo NOT NULL DEFAULT 'en_curso',
  "pago_id" uuid
);

CREATE UNIQUE INDEX ON "paradas_ruta" ("ruta_id", "secuencia");

CREATE INDEX ON "ubicaciones_ruta" ("ruta_id", "fecha_captura");

COMMENT ON COLUMN "empresas"."correo" IS 'HU-01: correo de confirmación';

COMMENT ON COLUMN "empresas"."tiene_flota_propia" IS 'HU-01: solo empresas con conductores propios';

COMMENT ON COLUMN "empresas"."configuracion" IS 'HU-24: configuración general de la empresa';

COMMENT ON COLUMN "empresas"."referencia_tarjeta" IS 'HU-37: referencia (token) de la tarjeta registrada en Wompi. No se guardan datos de la tarjeta (RNF11)';

COMMENT ON COLUMN "empresas"."tope_gasto_mensual" IS 'HU-39: tope opcional de gasto en pago por uso. NULL = sin tope';

COMMENT ON COLUMN "usuarios"."empresa_id" IS 'NULL para el admin del sistema';

COMMENT ON COLUMN "conductores"."estado" IS 'RF05: disponibilidad';

COMMENT ON TABLE "planes" IS 'HU-22. En pago por uso, precio_mensual es la membresía base. Todas las modalidades incluyen reportes avanzados';

COMMENT ON COLUMN "planes"."nombre" IS 'Free Trial | Básico | Pro | Premium | Pago por uso';

COMMENT ON COLUMN "planes"."max_conductores" IS 'Free Trial: 3, Básico: 3, Pro: 10, Premium: NULL (ilimitado)';

COMMENT ON COLUMN "planes"."max_sedes" IS 'Free Trial: 1, Básico: 1, Pro: 5, Premium: NULL (ilimitado)';

COMMENT ON COLUMN "planes"."tipo_soporte" IS 'Free Trial, Básico y Pro: correo o chat. Premium: dedicado';

COMMENT ON COLUMN "planes"."dias_prueba" IS 'Solo Free Trial: 7';

COMMENT ON COLUMN "planes"."creditos_mensuales" IS 'HU-16: solicitudes incluidas por mes. En Free Trial: total para los 7 días. Por definir';

COMMENT ON COLUMN "planes"."precio_mensual" IS 'Precio del plan mensual en COP. Por definir';

COMMENT ON COLUMN "planes"."precio_anual" IS 'Precio del plan anual en COP, con descuento. Por definir';

COMMENT ON COLUMN "planes"."conductores_incluidos" IS 'Solo pago por uso: conductores incluidos en la membresía. Por definir';

COMMENT ON COLUMN "planes"."precio_optimizacion" IS 'Solo pago por uso: precio por optimización exitosa. Por definir';

COMMENT ON COLUMN "planes"."precio_conductor_adicional" IS 'Solo pago por uso: precio mensual por conductor adicional. Por definir';

COMMENT ON COLUMN "planes"."monto_cobro_anticipado" IS 'Solo pago por uso: monto que dispara el cobro antes del cierre del mes. Por definir';

COMMENT ON TABLE "suscripciones" IS 'Historial de planes por empresa. Solo una activa por empresa: CREATE UNIQUE INDEX ON suscripciones (empresa_id) WHERE estado = ''activa''';

COMMENT ON COLUMN "suscripciones"."estado" IS 'activa: vigente. vencida: Free Trial terminado sin plan pago, plan no renovado o pago rechazado. inactiva: reemplazada por otro plan (historial)';

COMMENT ON COLUMN "suscripciones"."ciclo_facturacion" IS 'Mensual o anual. NULL en Free Trial y en pago por uso (siempre mensual)';

COMMENT ON COLUMN "suscripciones"."pago_id" IS 'Pago que la habilitó. NULL en Free Trial';

COMMENT ON COLUMN "suscripciones"."fecha_renovacion" IS 'Fin del periodo pagado (mensual o anual). En Free Trial: fecha de vencimiento';

COMMENT ON COLUMN "suscripciones"."fecha_fin" IS 'Fecha en que terminó la suscripción (historial)';

COMMENT ON TABLE "modulos" IS 'Módulos por sector (RF12: transporte escolar)';

COMMENT ON COLUMN "modulos"."codigo" IS 'Ej. escolar. Se pueden agregar sectores sin cambiar la estructura';

COMMENT ON COLUMN "modulos"."nombre" IS 'Ej. Transporte escolar';

COMMENT ON COLUMN "modulos"."precio" IS 'Precio mensual como adicional. Por definir';

COMMENT ON COLUMN "modulos"."activo" IS 'HU-22 CA04: dejar de ofrecerlo sin afectar a quienes ya lo tienen';

COMMENT ON TABLE "planes_modulos" IS 'Módulos incluidos en cada plan. Premium incluye el escolar; Free Trial lo incluye de prueba';

COMMENT ON TABLE "empresas_modulos" IS 'Módulos comprados aparte (solo plan Pro, validado en el sistema). Acceso al módulo = el plan lo incluye O la empresa lo compró';

COMMENT ON COLUMN "empresas_modulos"."pago_id" IS 'HU-19: se crea cuando la pasarela aprueba el pago';

COMMENT ON COLUMN "empresas_modulos"."precio" IS 'Precio pagado al adquirirlo';

COMMENT ON COLUMN "empresas_modulos"."fecha_fin" IS 'NULL = vigente';

COMMENT ON TABLE "saldos_creditos" IS 'HU-16 / HU-17: saldo actual, solo en la modalidad de suscripción. Cada optimización consume primero creditos_plan y luego creditos_extra';

COMMENT ON COLUMN "saldos_creditos"."creditos_plan" IS 'Se reinician cada mes al valor del plan, también en planes anuales. CHECK >= 0';

COMMENT ON COLUMN "saldos_creditos"."creditos_extra" IS 'Comprados. No se reinician. CHECK >= 0';

COMMENT ON TABLE "paquetes_creditos" IS 'HU-17 R02: definidos por el admin del sistema';

COMMENT ON COLUMN "paquetes_creditos"."creditos" IS 'HU-17: cantidad de solicitudes';

COMMENT ON COLUMN "paquetes_creditos"."precio" IS 'HU-17: precio';

COMMENT ON TABLE "compras_creditos" IS 'HU-18 R02: solo con suscripción activa y fuera del Free Trial (validado en el sistema)';

COMMENT ON COLUMN "compras_creditos"."pago_id" IS 'HU-18: se crea cuando la pasarela aprueba el pago';

COMMENT ON COLUMN "compras_creditos"."creditos" IS 'HU-18: cantidad adquirida';

COMMENT ON COLUMN "compras_creditos"."precio" IS 'Precio pagado al momento de la compra';

COMMENT ON COLUMN "compras_creditos"."fecha_compra" IS 'HU-18: fecha';

COMMENT ON TABLE "movimientos_creditos" IS 'HU-16 CA05: historial de movimientos';

COMMENT ON COLUMN "movimientos_creditos"."cantidad" IS 'Positiva: renovación o compra. Negativa: consumo';

COMMENT ON COLUMN "movimientos_creditos"."saldo_resultante" IS 'HU-18 CA03: saldo total resultante (plan + extra)';

COMMENT ON COLUMN "movimientos_creditos"."compra_id" IS 'Solo si tipo = compra';

COMMENT ON COLUMN "movimientos_creditos"."optimizacion_id" IS 'Solo si tipo = consumo';

COMMENT ON COLUMN "ordenes"."direccion" IS 'RF04';

COMMENT ON COLUMN "ordenes"."latitud" IS 'RF15';

COMMENT ON COLUMN "ordenes"."longitud" IS 'RF15';

COMMENT ON COLUMN "ordenes"."prioridad" IS 'RF04';

COMMENT ON COLUMN "rutas"."conductor_id" IS 'RF09';

COMMENT ON COLUMN "rutas"."latitud_inicio" IS 'RF06: punto de partida del conductor';

COMMENT ON COLUMN "rutas"."fecha_inicio" IS 'Momento en que el conductor inicia la ruta';

COMMENT ON COLUMN "rutas"."fecha_fin" IS 'Momento en que el conductor finaliza la ruta';

COMMENT ON TABLE "paradas_ruta" IS 'Cada parada tiene orden_id o estudiante_id (uno de los dos)';

COMMENT ON COLUMN "paradas_ruta"."orden_id" IS 'NULL si es parada escolar';

COMMENT ON COLUMN "paradas_ruta"."estudiante_id" IS 'NULL si es orden';

COMMENT ON COLUMN "paradas_ruta"."secuencia" IS 'RF06 / RF09: orden de visita';

COMMENT ON COLUMN "paradas_ruta"."fecha_llegada" IS 'RF14: llegada a la parada';

COMMENT ON COLUMN "paradas_ruta"."verificada_geocerca" IS 'RF14: true si la llegada la detectó el GPS';

COMMENT ON COLUMN "paradas_ruta"."fecha_confirmacion" IS 'RF10 / HU-15: hora real de la confirmación en el dispositivo';

COMMENT ON COLUMN "paradas_ruta"."fecha_sincronizacion" IS 'RF17: hora en que llegó al servidor (modo offline)';

COMMENT ON COLUMN "paradas_ruta"."observaciones" IS 'Observaciones del conductor';

COMMENT ON COLUMN "optimizaciones_ruta"."distancia_total_m" IS 'HU-07 / HU-08';

COMMENT ON COLUMN "optimizaciones_ruta"."duracion_estimada_s" IS 'HU-07 / HU-08';

COMMENT ON COLUMN "optimizaciones_ruta"."tiempo_procesamiento_ms" IS 'RNF01: máx. 10 s';

COMMENT ON COLUMN "optimizaciones_ruta"."exitosa" IS 'Una optimización fallida no consume crédito ni se cobra';

COMMENT ON COLUMN "optimizaciones_ruta"."cobro_consumo_id" IS 'Solo pago por uso: cobro en el que se incluye esta optimización';

COMMENT ON TABLE "ubicaciones_ruta" IS 'RF13 / HU-36: recorrido GPS completo de cada ruta en curso (un punto cada 30 s aprox.). La ubicación en vivo cada 5 s va en Redis';

COMMENT ON COLUMN "ubicaciones_ruta"."fecha_captura" IS 'Hora real en que se tomó el punto en el dispositivo';

COMMENT ON COLUMN "ubicaciones_ruta"."fecha_sincronizacion" IS 'Hora en que llegó al servidor';

COMMENT ON COLUMN "ubicaciones_ruta"."sin_conexion" IS 'true si se tomó sin conexión';

COMMENT ON COLUMN "fotos_entrega"."url_foto" IS 'RF16: dirección del archivo, no la imagen';

COMMENT ON COLUMN "incidencias"."ruta_id" IS 'El conductor que reporta es el de la ruta';

COMMENT ON COLUMN "incidencias"."parada_id" IS 'Parada afectada, si aplica';

COMMENT ON COLUMN "incidencias"."clase" IS 'HU-11: incidencia o duda';

COMMENT ON TABLE "mensajes_incidencia" IS 'HU-11: comunicación conductor-supervisor';

COMMENT ON COLUMN "mensajes_incidencia"."remitente_id" IS 'Conductor o supervisor';

COMMENT ON TABLE "solicitudes_soporte" IS 'HU-03 / HU-34: soporte técnico';

COMMENT ON COLUMN "solicitudes_soporte"."respuesta" IS 'HU-03: respuesta del admin del sistema';

COMMENT ON TABLE "alertas_sistema" IS 'HU-02: historial de fallos y alertas del sistema';

COMMENT ON COLUMN "alertas_sistema"."empresa_id" IS 'NULL si afecta a toda la plataforma';

COMMENT ON COLUMN "alertas_sistema"."origen" IS 'Componente que generó la alerta';

COMMENT ON TABLE "configuracion_sistema" IS 'HU-23: parámetros generales de la plataforma';

COMMENT ON COLUMN "configuracion_sistema"."clave" IS 'Nombre del parámetro';

COMMENT ON COLUMN "configuracion_sistema"."valor" IS 'Valor del parámetro';

COMMENT ON TABLE "notificaciones" IS 'HU-03, HU-11, HU-16 CA03 y CA07, HU-18, HU-31, HU-33, HU-37 y HU-39: avisos dentro de la plataforma';

COMMENT ON TABLE "estudiantes" IS 'RF12 / HU-32: requiere el módulo escolar (incluido en Premium, comprado en Pro o de prueba en Free Trial)';

COMMENT ON COLUMN "estudiantes"."direccion_recogida" IS 'RF12: punto de recogida';

COMMENT ON TABLE "pagos" IS 'HU-18, HU-19, HU-33, HU-37: pagos en línea por Wompi. La compra se habilita solo con estado = aprobado. No se guardan datos de tarjetas (RNF11)';

COMMENT ON COLUMN "pagos"."concepto" IS 'Suscripción, paquete de créditos, módulo o consumo';

COMMENT ON COLUMN "pagos"."monto" IS 'Monto en COP';

COMMENT ON COLUMN "pagos"."medio_pago" IS 'Ej. tarjeta, pse, nequi. Más adelante: efectivo';

COMMENT ON COLUMN "pagos"."referencia_pasarela" IS 'Referencia de la transacción en la pasarela';

COMMENT ON TABLE "cobros_consumo" IS 'HU-37 / HU-38: consumo acumulado del pago por uso. Se cobra al cierre del mes o al alcanzar el monto de cobro anticipado';

COMMENT ON COLUMN "cobros_consumo"."fecha_fin_periodo" IS 'Cierre del mes o fecha en que se alcanzó el monto de cobro anticipado';

COMMENT ON COLUMN "cobros_consumo"."monto" IS 'Monto acumulado en COP';

COMMENT ON COLUMN "cobros_consumo"."pago_id" IS 'Pago con el que se cobró. NULL mientras está en curso';

ALTER TABLE "sedes" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conductores" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suscripciones" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suscripciones" ADD FOREIGN KEY ("plan_id") REFERENCES "planes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suscripciones" ADD FOREIGN KEY ("pago_id") REFERENCES "pagos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "planes_modulos" ADD FOREIGN KEY ("plan_id") REFERENCES "planes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "planes_modulos" ADD FOREIGN KEY ("modulo_id") REFERENCES "modulos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "empresas_modulos" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "empresas_modulos" ADD FOREIGN KEY ("modulo_id") REFERENCES "modulos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "empresas_modulos" ADD FOREIGN KEY ("pago_id") REFERENCES "pagos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saldos_creditos" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compras_creditos" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compras_creditos" ADD FOREIGN KEY ("paquete_id") REFERENCES "paquetes_creditos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compras_creditos" ADD FOREIGN KEY ("pago_id") REFERENCES "pagos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimientos_creditos" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimientos_creditos" ADD FOREIGN KEY ("compra_id") REFERENCES "compras_creditos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimientos_creditos" ADD FOREIGN KEY ("optimizacion_id") REFERENCES "optimizaciones_ruta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ordenes" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ordenes" ADD FOREIGN KEY ("sede_id") REFERENCES "sedes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rutas" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rutas" ADD FOREIGN KEY ("conductor_id") REFERENCES "conductores" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paradas_ruta" ADD FOREIGN KEY ("ruta_id") REFERENCES "rutas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paradas_ruta" ADD FOREIGN KEY ("orden_id") REFERENCES "ordenes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paradas_ruta" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "optimizaciones_ruta" ADD FOREIGN KEY ("ruta_id") REFERENCES "rutas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "optimizaciones_ruta" ADD FOREIGN KEY ("cobro_consumo_id") REFERENCES "cobros_consumo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ubicaciones_ruta" ADD FOREIGN KEY ("ruta_id") REFERENCES "rutas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fotos_entrega" ADD FOREIGN KEY ("parada_id") REFERENCES "paradas_ruta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "incidencias" ADD FOREIGN KEY ("ruta_id") REFERENCES "rutas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "incidencias" ADD FOREIGN KEY ("parada_id") REFERENCES "paradas_ruta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensajes_incidencia" ADD FOREIGN KEY ("incidencia_id") REFERENCES "incidencias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensajes_incidencia" ADD FOREIGN KEY ("remitente_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitudes_soporte" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alertas_sistema" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificaciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estudiantes" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pagos" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cobros_consumo" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cobros_consumo" ADD FOREIGN KEY ("pago_id") REFERENCES "pagos" ("id") DEFERRABLE INITIALLY IMMEDIATE;
